base_url = "https://tam.games"
title = "tam.games"
author = "Tam"

generate_feed = true

compile_sass = true
minify_html = true

build_search_index = false

external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer = true

[markdown]
highlight_code = true
highlight_theme = "ayu-dark"

[extra]
